networks:
  app-network:
    driver: bridge

services:
  donut_api:
    build:
      context: ./donut_api
      dockerfile: Dockerfile
    networks:
      - app-network
    container_name: donut_api
    volumes:
      - ./ocr_model/model:/app/model   # Mount local ocr_model/ to /model in donut_api container

  vessel:
    build:
      context: ./vessel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    container_name: vessel
    volumes:
      - ./det_models:/app/yolo   # Mount local det_models/ to /yolo in vessel container
      - ./output:/app/output
